---
- hosts: all
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Copy module
      copy:
        src: "../{{ module }}"
        dest: "{{ dest }}"

    - name: Restart z-way-server
      service:
        name: z-way-server
        state: restarted
      become: True