---
- hosts: all
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Copy module
      copy:
        src: "../modules/{{ module }}/"
        dest: "{{ dest }}{{ module }}/"

    - name: Restart z-way-server
      service:
        name: z-way-server
        state: restarted
      become: True